name: yousef walid omar section 5

on:
  push:
    branches:
      - master  
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: pwd

        name: Checkout printing
        run: echo yousef_walid
      
