name: yousef walid omar section 5

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:  # Trigger on pull requests
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        run: pwd

        name: Checkout printing
        run: echo yousef_walid
      # Step 2: Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t your_dockerhub_username/your_image_name:latest .

      # Step 4: Push the Docker image (optional)
      - name: Push Docker Image
        run: |
          docker push your_dockerhub_username/your_image_name:latest
