name: yousef walid omar section 5

on:
  push:
    branches:
      - master  
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: befor
        run: ls

      - uses: actions/checkout@v3

      - name: after
        run: ls
      
